# Generated by Django 4.1.10 on 2023-08-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.BigIntegerField(default=0),
        ),
    ]
