# Generated by Django 4.1.10 on 2023-09-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='user/pictures'),
        ),
    ]
